# Pandas practice for Data Science

## Series object

In [5]:
import pandas as pd
# one domensional array
s1 = pd.Series([1,2,3,4,5,6])
# Display series
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [4]:
# check what type of data is s1
type(s1)

pandas.core.series.Series

In [10]:
# attaching a specific index
# index to be written inside pd.Series function, separated by a comma
s1 = pd.Series([1,2,3,4,5,6], index = ['a', 'b', 'c', 'd', 'e', 'f'])
s1

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [11]:
# another way to introduce index
pd.Series({'a' :10, 'b' : 20, 'c' : 30})

a    10
b    20
c    30
dtype: int64

In [14]:
# changing index
s2 = pd.Series({'a' :10, 'b' : 20, 'c' : 30}, index=['b', 'c', 'd', 'a'])
s2

b    20.0
c    30.0
d     NaN
a    10.0
dtype: float64

In [17]:
# extracting values from series with index 
s3 = [1,2,3,4,5,6,7,8,9]
s3[1]

2

In [20]:
# extract values from 1 till 3(except index 3)
s3 = [1,2,3,4,5,6,7,8,9]
s3[1:3]

[2, 3]

In [21]:
# extract values from index 0 till 3(except index 3)
s3 = [1,2,3,4,5,6,7,8,9]
s3[:3]

[1, 2, 3]

In [22]:
s3 = [1,2,3,4,5,6,7,8,9]
s3[:-1]

[1, 2, 3, 4, 5, 6, 7, 8]

In [23]:
s3 = [1,2,3,4,5,6,7,8,9]
s3[1:-2]
# last index represents -1

[2, 3, 4, 5, 6, 7]

In [24]:
s3 = [1,2,3,4,5,6,7,8,9]
s3[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
# print values from index -2(second last value) till end
s3 = [1,2,3,4,5,6,7,8,9]
s3[-2:]

[8, 9]

# # Arithmatic operations on series elements

In [33]:
s4 = pd.Series([1,2,3,4,5,6,7,8,9])
s4 +2

0     3
1     4
2     5
3     6
4     7
5     8
6     9
7    10
8    11
dtype: int64

In [36]:
s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s6 = pd.Series([1,2,3,4,5,6,7,8,9])
s5 + s6

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    16
8    18
dtype: int64

In [37]:
s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s6 = pd.Series([1,2,3,4,5,6,7,8,9])
s5 - s6

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [38]:
s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s6 = pd.Series([1,2,3,4,5,6,7,8,9])
s5 / s6

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
8    1.0
dtype: float64

In [39]:
s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s6 = pd.Series([1,2,3,4,5,6,7,8,9])
s5 * s6

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
dtype: int64

In [43]:
s5 = pd.Series([1,2,3,4,5,6,7,8,9])
s6 = pd.Series([1,1,3,4,6,6,9,8,5])
s5 > s6

0    False
1     True
2    False
3    False
4    False
5    False
6    False
7    False
8     True
dtype: bool

## Creating 2d Data frame

In [44]:
import pandas as pd
# Create data frame using dictonary, key1 is name with values ram, shyam, mohan & key2 is marks with values 10, 15 & 19 
pd.DataFrame({'name':['ram', 'shyam', 'mohan'], 'marks':[10, 15, 19]})

   marks   name
0     10    ram
1     15  shyam
2     19  mohan

## Builtin functions

### shape() : shows no of rows & columns of a data frame 
### head() : displays first 5 rows of data frame
### tail() : displays last 5 rows of data frame
### describe() : displays general info

In [48]:
# using Iris.csv dataset 
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [49]:
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [52]:
iris.shape
# without ()

(150, 6)

In [54]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

### iloc[] : to extract a part of data from given data frame

In [61]:
# extract first 3 rows & firat 2 columns
iris = pd.read_csv('Iris.csv')
iris.iloc[0:3,0:4]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm
0   1            5.1           3.5            1.4
1   2            4.9           3.0            1.4
2   3            4.7           3.2            1.3

In [65]:
# extract rows 5 till 10(except10) & column 3 till 5(i.e.3 & 4th)
iris.iloc[5:10,3:5]

   PetalLengthCm  PetalWidthCm
5            1.7           0.4
6            1.4           0.3
7            1.5           0.2
8            1.4           0.2
9            1.5           0.1

### loc[] : similar to iloc[] method but here we use column name insted of index

In [68]:
iris.loc[5:10, ('PetalLengthCm', 'PetalWidthCm', 'Species')]
# note: in iloc for row index last value is not included while in loc it goes till last row index. see above & below examples

    PetalLengthCm  PetalWidthCm      Species
5             1.7           0.4  Iris-setosa
6             1.4           0.3  Iris-setosa
7             1.5           0.2  Iris-setosa
8             1.4           0.2  Iris-setosa
9             1.5           0.1  Iris-setosa
10            1.5           0.2  Iris-setosa

### Drop rows/columns
#### axis=0 will drop rows, axis=1 will drop columns

In [74]:
# drop columns by name(here Species)
iris.drop('Species', axis=1)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
5      6            5.4           3.9            1.7           0.4
6      7            4.6           3.4            1.4           0.3
7      8            5.0           3.4            1.5           0.2
8      9            4.4           2.9            1.4           0.2
9     10            4.9           3.1            1.5           0.1
10    11            5.4           3.7            1.5           0.2
11    12            4.8           3.4            1.6           0.2
12    13            4.8           3.0            1.4           0.1
13    14            4.3           3.0            1.1           0.1
14    15            5.8           4.0            1.2           0.2
15    16            5.7           4.4            1.5           0.4
16    17            5.4           3.9            1.3           0.4
17    18            5.1           3.5            1.4           0.3
18    19            5.7           3.8            1.7           0.3
19    20            5.1           3.8            1.5           0.3
20    21            5.4           3.4            1.7           0.2
21    22            5.1           3.7            1.5           0.4
22    23            4.6           3.6            1.0           0.2
23    24            5.1           3.3            1.7           0.5
24    25            4.8           3.4            1.9           0.2
25    26            5.0           3.0            1.6           0.2
26    27            5.0           3.4            1.6           0.4
27    28            5.2           3.5            1.5           0.2
28    29            5.2           3.4            1.4           0.2
29    30            4.7           3.2            1.6           0.2
..   ...            ...           ...            ...           ...
120  121            6.9           3.2            5.7           2.3
121  122            5.6           2.8            4.9           2.0
122  123            7.7           2.8            6.7           2.0
123  124            6.3           2.7            4.9           1.8
124  125            6.7           3.3            5.7           2.1
125  126            7.2           3.2            6.0           1.8
126  127            6.2           2.8            4.8           1.8
127  128            6.1           3.0            4.9           1.8
128  129            6.4           2.8            5.6           2.1
129  130            7.2           3.0            5.8           1.6
130  131            7.4           2.8            6.1           1.9
131  132            7.9           3.8            6.4           2.0
132  133            6.4           2.8            5.6           2.2
133  134            6.3           2.8            5.1           1.5
134  135            6.1           2.6            5.6           1.4
135  136            7.7           3.0            6.1           2.3
136  137            6.3           3.4            5.6           2.4
137  138            6.4           3.1            5.5           1.8
138  139            6.0           3.0            4.8           1.8
139  140            6.9           3.1            5.4           2.1
140  141            6.7           3.1            5.6           2.4
141  142            6.9           3.1            5.1           2.3
142  143            5.8           2.7            5.1           1.9
143  144            6.8           3.2            5.9           2.3
144  145            6.7           3.3            5.7           2.5
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [78]:
# drop rows by index(here index 0 till 3 will be dropped)
iris.drop([1,2,3], axis=0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
16,17,5.4,3.9,1.3,0.4,Iris-setosa
17,18,5.1,3.5,1.4,0.3,Iris-setosa
18,19,5.7,3.8,1.7,0.3,Iris-setosa
19,20,5.1,3.8,1.5,0.3,Iris-setosa
20,21,5.4,3.4,1.7,0.2,Iris-setosa
21,22,5.1,3.7,1.5,0.4,Iris-setosa
22,23,4.6,3.6,1.0,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
26,27,5.0,3.4,1.6,0.4,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
31,32,5.4,3.4,1.5,0.4,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
...,...,...,...,...,...,...
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

### mean, median, minimum, maximum

In [80]:
iris.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [81]:
iris.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [82]:
iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object

In [83]:
iris.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [84]:
iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

### operation on column values(reducing values etc)

In [85]:
# reduce SepalLengthCm &  PetalLengthCm value to half by user defined function
def reduce_by_half(x):
    return x * 0.5
iris[['SepalLengthCm', 'PetalLengthCm']].apply(reduce_by_half)

     SepalLengthCm  PetalLengthCm
0             2.55           0.70
1             2.45           0.70
2             2.35           0.65
3             2.30           0.75
4             2.50           0.70
5             2.70           0.85
6             2.30           0.70
7             2.50           0.75
8             2.20           0.70
9             2.45           0.75
10            2.70           0.75
11            2.40           0.80
12            2.40           0.70
13            2.15           0.55
14            2.90           0.60
15            2.85           0.75
16            2.70           0.65
17            2.55           0.70
18            2.85           0.85
19            2.55           0.75
20            2.70           0.85
21            2.55           0.75
22            2.30           0.50
23            2.55           0.85
24            2.40           0.95
25            2.50           0.80
26            2.50           0.80
27            2.60           0.75
28            2.60           0.70
29            2.35           0.80
..             ...            ...
120           3.45           2.85
121           2.80           2.45
122           3.85           3.35
123           3.15           2.45
124           3.35           2.85
125           3.60           3.00
126           3.10           2.40
127           3.05           2.45
128           3.20           2.80
129           3.60           2.90
130           3.70           3.05
131           3.95           3.20
132           3.20           2.80
133           3.15           2.55
134           3.05           2.80
135           3.85           3.05
136           3.15           2.80
137           3.20           2.75
138           3.00           2.40
139           3.45           2.70
140           3.35           2.80
141           3.45           2.55
142           2.90           2.55
143           3.40           2.95
144           3.35           2.85
145           3.35           2.60
146           3.15           2.50
147           3.25           2.60
148           3.10           2.70
149           2.95           2.55

[150 rows x 2 columns]

### .value_counts() : Value count

In [86]:
iris['Species'].value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

### .sort_values() : increasing order

In [87]:
iris.head(10)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [90]:
# sort PetalWidthCm in increasing order of values
iris.sort_values(by='PetalWidthCm')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
32,33,5.2,4.1,1.5,0.1,Iris-setosa
13,14,4.3,3.0,1.1,0.1,Iris-setosa
37,38,4.9,3.1,1.5,0.1,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
34,35,4.9,3.1,1.5,0.1,Iris-setosa
0,1,5.1,3.5,1.4,0.2,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
36,37,5.5,3.5,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
39,40,5.1,3.4,1.5,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
46,47,5.1,3.8,1.6,0.2,Iris-setosa
47,48,4.6,3.2,1.4,0.2,Iris-setosa
48,49,5.3,3.7,1.5,0.2,Iris-setosa
49,50,5.0,3.3,1.4,0.2,Iris-setosa
25,26,5.0,3.0,1.6,0.2,Iris-setosa
24,25,4.8,3.4,1.9,0.2,Iris-setosa
35,36,5.0,3.2,1.2,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
...,...,...,...,...,...,...
111,112,6.4,2.7,5.3,1.9,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
100,101,6.3,3.3,6.0,2.5,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica